services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  JojoRender\:
    resource: '../../../../vendor/ben-balke/jojo-render/src/*'

  JojoSuiteCRM\EmailParser\JojoEmailParser:
    tags:
    - { name: email.parser }
    arguments:
      $jojo: '@JojoRender\Jojo'